import type { NextPage } from 'next'
import Head from 'next/head'
import Access from '@components/Access'
import Card from '@components/Card'

const item = {
    title: 'Coffee Mug - Card',
    pretitle: 'maci',
    img: {
        src: 'https://picsum.photos/200/300'
    }
}

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <Access url='/'>
            <Card item={item}>
                <Card.Image />
                <Card.Title /> 
                <Card.Pretitle />
            </Card>
        </Access>

        
      </main>
    </div>
  )
}

export default Home
